name: Build docker container and push to registry with cache

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io # Github Container Registry
  REPOSITORY: ${{ github.repository }} # Repository name
  REGISTRY_USERNAME: ${{ github.actor }} # Github username
  REGISTRY_PASSWORD: ${{ secrets.GHCR }} # Personal access token

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: nginx # Name of the service in the docker-compose file
      DOCKERFILE_LOCATION: server/nginx # Path to Dockerfile directory in the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login --username ${{ env.REGISTRY_USERNAME }} --password ${{ env.REGISTRY_PASSWORD }} ${{ env.REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build ${{ env.DOCKERFILE_LOCATION }} \
            --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.SERVICE_NAME }} \
            --cache-from type=registry,ref=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.SERVICE_NAME }}-cache \
            --cache-to type=registry,ref=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.SERVICE_NAME }}-cache,mode=max \
            --push
