version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - default

  wordpress:
    image: wordpress:6.0.3-php8.1-apache
    volumes:
      - wordpress:/var/www/html
      - /root/wordpress_custom_php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - /root/wordpress_plugins:/usr/src/wordpress/wp-content/plugins
      - /root/wordpress_themes:/usr/src/wordpress/wp-content/themes
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
      VIRTUAL_PORT: 80
    networks:
      - proxy
      - default

volumes:
  database:
  wordpress:

networks:
  proxy:
    external:
      name: nginx-proxy
