name: Build neovim

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io # Github Container Registry
  IMAGE_TAG: main
  REPOSITORY: ${{ github.repository }}
  REGISTRY_USERNAME: ${{ github.actor }} # Github username
  REGISTRY_PASSWORD: ${{ secrets.GHCR }} # Personal access token

jobs:
  neovim: # Job name for building image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: neovim # Name of the image
      BUILD_LOCATION: configs/neovim # Path to Dockerfile in the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login --username ${{ env.REGISTRY_USERNAME }} --password ${{ env.REGISTRY_PASSWORD }} ${{ env.REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build ${{ env.BUILD_LOCATION }} \
            --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --cache-from type=registry,ref=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}-${{ env.IMAGE_NAME }}-cache \
            --cache-to type=registry,ref=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}-${{ env.IMAGE_NAME }}-cache,mode=max \
            --push
