name: Generate state

on:
  schedule:
    - cron: '0 20 * * 0'

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Stats
        uses: UlyssesZh/grs-action@v0
        with:
          card: stats
          options: username=${{ github.repository_owner }}
          path: grs/stats.svg
        env:
          PAT_1: ${{ secrets.GITHUB_TOKEN }}

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
