name: Statistics

on:
  schedule:
    - cron: '0 20 * * 0'

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Lang Stats
        uses: UlyssesZh/grs-action@v0
        with:
          card: langs
          options: username=${{ github.repository_owner }}&layout=compact&hide_title=true&hide=tex,html&langs_count=14&hide_border=true
          path: grs/langs.svg
        env:
          PAT_1: ${{ secrets.TOKEN }}

      - name: Generate Lang Stats
        uses: UlyssesZh/grs-action@v0
        with:
          card: langs
          options: username=${{ github.repository_owner }}&layout=compact&hide_title=true&hide=tex,html&langs_count=14&hide_border=true&theme=dark
          path: grs/langs-dark.svg
        env:
          PAT_1: ${{ secrets.TOKEN }}

      - name: Generate General Stats
        uses: UlyssesZh/grs-action@v0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&layout=compact&hide_title=true&hide=tex,html&langs_count=16&hide_border=true&disable_animations=true
          path: grs/stats.svg
        env:
          PAT_1: ${{ secrets.TOKEN }}

      - name: Generate General Stats
        uses: UlyssesZh/grs-action@v0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&layout=compact&hide_title=true&hide=tex,html&langs_count=16&hide_border=true&disable_animations=true&theme=dark
          path: grs/stats-dark.svg
        env:
          PAT_1: ${{ secrets.TOKEN }}

      - name: push stats to the stats branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: stats
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
